# Generated by Django 3.1.2 on 2022-07-14 17:55

import car_finder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lxy5RTymtFTMKIDHlEluIpoXIIiqO3y6', max_length=100)),
                ('image', models.ImageField(upload_to=car_finder.models.image_path)),
                ('output_image', models.ImageField(default=None, upload_to=car_finder.models.output_image_path)),
                ('number_of_cars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
